### ISSUE TITLE
Error conda.yml

### ISSUE THREAD

**Issue by 1treu1** [PaccMann/paccmann_proteomics#4] opened 2021-11-09 18:47 UTC
Hello, greetings from Colombia.
I have reviewed your work and it is very interesting.
I wanted to create the environment with the file conda.yml but when installing "-e ." gives the following error:
////////////////////////////////////////////////////////
ERROR: Cannot install paccmann-proteomics and paccmann-proteomics==0.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    paccmann-proteomics 0.0.1 depends on tokenizers==0.8.0
    transformers 3.0.2 depends on tokenizers==0.8.1.rc1

To fix this you could try
1. loosen the range of package versions you have specified.
2. remove the package versions to allow pip to attempt to resolve the dependency conflict.

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
//////////////////////////////////////////////////////////
I have tried installing a newer version of tokenizers and transformers but still get the same error.
Do you happen to have any idea how to fix this problem?

**Comment by drugilsberg** [comment] 2021-11-10 19:41
I saw the other issue. Is this one still persisting? If not feel free to close it.

**Comment by 1treu1** [comment] 2021-11-10 20:33
I still have the same problem

**Comment by jannisborn** [comment] 2021-11-10 20:42
this issue is caused by the unbounded pip version in the `conda.yml`. Some time around `pip`version 20.3 there was a stricter dependency resolver introduced that causes the failure here. Pls edit the yml file like this:
```yml
  - pip>=19.1,<20.3
  ```

I will prepare a PR

**Comment by jannisborn** [comment] 2021-11-10 20:45
Ok, just merged the PR. Can you please pull the latest code and install the package again? 
It might still give you warnings but the installation should successfully complete.
Please then verify whether the other issue persists.

**Closed as completed by jannisborn** 2021-11-10 20:45 UTC
